/**
 * My API
 * API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

import * as api from "./api"
import { Configuration } from "./configuration"

const config: Configuration = {}

describe("DefaultApi", () => {
  let instance: api.DefaultApi
  beforeEach(function() {
    instance = new api.DefaultApi(config)
  });

  test("appControllerGetHello", () => {
    return expect(instance.appControllerGetHello({})).resolves.toBe(null)
  })
  test("authControllerLogin", () => {
    return expect(instance.authControllerLogin({})).resolves.toBe(null)
  })
})

describe("UsersApi", () => {
  let instance: api.UsersApi
  beforeEach(function() {
    instance = new api.UsersApi(config)
  });

  test("usersControllerCreate", () => {
    const body: api.CreateUserDto = undefined
    return expect(instance.usersControllerCreate(body, {})).resolves.toBe(null)
  })
  test("usersControllerFindAll", () => {
    return expect(instance.usersControllerFindAll({})).resolves.toBe(null)
  })
  test("usersControllerFindOne", () => {
    const id: string = "id_example"
    return expect(instance.usersControllerFindOne(id, {})).resolves.toBe(null)
  })
  test("usersControllerRemove", () => {
    const id: string = "id_example"
    return expect(instance.usersControllerRemove(id, {})).resolves.toBe(null)
  })
  test("usersControllerUpdate", () => {
    const body: api.UpdateUserDto = undefined
    const id: string = "id_example"
    return expect(instance.usersControllerUpdate(body, id, {})).resolves.toBe(null)
  })
})

