// styles/fonts.ts
export const fonts = {
	black: "Poppins-Black",
	blackItalic: "Poppins-BlackItalic",
	bold: "Poppins-Bold",
	boldItalic: "Poppins-BoldItalic",
	extraBold: "Poppins-ExtraBold",
	extraBoldItalic: "Poppins-ExtraBoldItalic",
	extraLight: "Poppins-ExtraLight",
	extraLightItalic: "Poppins-ExtraLightItalic",
	italic: "Poppins-Italic",
	light: "Poppins-Light",
	lightItalic: "Poppins-LightItalic",
	medium: "Poppins-Medium",
	mediumItalic: "Poppins-MediumItalic",
	regular: "Poppins-Regular",
	semiBold: "Poppins-SemiBold",
	semiBoldItalic: "Poppins-SemiBoldItalic",
	thin: "Poppins-Thin",
	thinItalic: "Poppins-ThinItalic",
};
