name: Deploy to EC2

on:
  push:
    branches: [ main, develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout "${{ github.repository }}"
      uses: actions/checkout@v3

    - name: Set up Node (stable)
      uses: actions/setup-node@v4
      with:
        node-version: 20.16

    - name: Create backend env file
      run: |
        touch backend/.env
        echo "${{ secrets.BACKEND_ENV_FILE }}" > backend/.env
      shell: bash

    - name: Install dependencies
      run:  |
        cd backend && npm ci

    - name: Last linting check before deployment
      run: cd backend && npm run lint

    - name: Last tests before deployment
      run: cd backend && npm run test

    - name: Verify Build before deployment
      run: |
        cd backend && npm run build:swc
        if [ ! -f "backend/dist/src/main.js" ]; then
          echo "Build failed: main.js not found!"
          exit 1
        fi

    - name: Install SSH Key
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          # Load NVM manually
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
          [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

          # Set memory limit manually
          export NODE_OPTIONS="--max-old-space-size=512"

          cd TuneIn/
          git checkout develop
          git fetch
          git pull
          cd backend
          echo "${{ secrets.BACKEND_ENV_FILE }}" > .env
          chmod +x start_backend.sh
          nvm use default
          npm i
          npm run build:swc
          ./start_backend.sh
        EOF

    - name: Health Check
      run: |
        curl --fail "https://tunein.co.za:3000/" || exit 1