name: Deploy to EC2

on:
  push:
    branches: [ main, develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout "${{ github.repository }}"
      uses: actions/checkout@v3

    - name: Set up Node (stable)
      uses: actions/setup-node@v4
      with:
        node-version: 20.16

    - name: Install dependencies
      run:  |
        cd frontend && npm ci

    - name: Last linting check before deployment
      run: npm run lint

    - name: Last tests before deployment
      run: npm run test

    - name: Verify Build before deployment
      run: |
        npm run build:swc
        if [ ! -f "backend/dist/src/main.js" ]; then
          echo "Build failed: main.js not found!"
          exit 1
        fi

    - name: Install SSH Key
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd TuneIn/
          echo "${{ secrets.BACKEND_ENV_FILE }}" > backend/.env
          git fetch
          git pull
          cd backend
          nvm use default
          npm i
          npm run build:swc
          pm2 restart tunein-backend
        EOF

    - name: Health Check
      run: |
        curl --fail "https://tunein.co.za:3000/" || exit 1