name: Lint Codebase
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
    #types: [opened, synchronize, reopened, ready_for_review]
permissions:
  contents: write

jobs:
  start:
    name: Initial Setup
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Starting Job
        run: |
          echo "Beginning to lint ${{ github.repository }}"

  lint_frontend:
    name: Lint Frontend
    runs-on: ubuntu-latest
    needs: start
    steps:
      - name: Checkout "${{ github.repository }}"
        uses: actions/checkout@v3
      - name: Set up Node (stable)
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run:  |
          cd frontend && npm ci

      - name: Auto-fix Frontend Linting
        run:  |
          cd frontend && npm run lint-fix

      - name: Commit fixes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add -A
          # Check if there are changes and only commit if so
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto-fix frontend linting issues"
            # Only push if commit was successful
            git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref }}
          fi

      - name: Run Frontend Linting
        run: |
          cd frontend && npm run lint

  lint_backend:
    name: Lint Backend
    runs-on: ubuntu-latest
    needs: start
    steps:
      - name: Checkout "${{ github.repository }}"
        uses: actions/checkout@v3
      - name: Set up Node (stable)
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run:  |
          cd backend && npm ci

      - name: Auto-fix Backend Linting
        run:  |
          cd backend && npm run lint-fix

      - name: Commit fixes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add -A
          # Check if there are changes and only commit if so
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto-fix frontend linting issues"
            # Only push if commit was successful
            git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref }}
          fi

      - name: Run Backend Linting
        run:  |
          cd backend && npm run lint
  
  end:
    name: The end
    runs-on: ubuntu-latest
    needs: [lint_frontend, lint_backend]
    steps:
      - name: Ending
        id: init
        run: |
          echo "${{ github.repository }} has been successfully linted"
